"""make_subcategory_id_optional

Revision ID: a1fc627b1f96
Revises: flexible_product_system_001
Create Date: 2025-09-03 09:00:57.181549

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1fc627b1f96'
down_revision: Union[str, Sequence[str], None] = 'flexible_product_system_001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('product', 'category_id',
               existing_type=sa.CHAR(length=32),
               nullable=True)
    op.alter_column('product', 'sku',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index(op.f('ix_product_name'), 'product', ['name'], unique=False)
    op.create_index(op.f('ix_product_sku'), 'product', ['sku'], unique=True)
    op.create_foreign_key(None, 'product', 'productcategory', ['category_id'], ['id'])
    op.create_foreign_key(None, 'product', 'productsubcategory', ['subcategory_id'], ['id'])
    op.drop_column('product', 'phone_model')
    op.drop_column('product', 'part_type')
    op.drop_column('product', 'variant')
    op.drop_index(op.f('ix_productattributedefinition_subcategory_id'), table_name='productattributedefinition')
    op.create_foreign_key(None, 'productattributedefinition', 'productsubcategory', ['subcategory_id'], ['id'])
    op.drop_index(op.f('ix_productsubcategory_category_id'), table_name='productsubcategory')
    op.create_foreign_key(None, 'productsubcategory', 'productcategory', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'productsubcategory', 'productcategory', ['category_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_productsubcategory_category_id'), 'productsubcategory', ['category_id'], unique=False)
    op.create_foreign_key(None, 'productattributedefinition', 'productsubcategory', ['subcategory_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_productattributedefinition_subcategory_id'), 'productattributedefinition', ['subcategory_id'], unique=False)
    op.add_column('product', sa.Column('variant', sa.VARCHAR(), nullable=False))
    op.add_column('product', sa.Column('part_type', sa.VARCHAR(), nullable=False))
    op.add_column('product', sa.Column('phone_model', sa.VARCHAR(), nullable=False))
    op.drop_index(op.f('ix_product_sku'), table_name='product')
    op.drop_index(op.f('ix_product_name'), table_name='product')
    op.alter_column('product', 'sku',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('product', 'category_id',
               existing_type=sa.CHAR(length=32),
               nullable=False)
    op.alter_column('product', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
