"""initial_tables

Revision ID: e3574c3fcfb1
Revises:
Create Date: 2025-09-01 15:56:31.786822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e3574c3fcfb1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expense',
    sa.Column('expense_date', sa.Date(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('category', sa.Enum('rent', 'utilities', 'supplies', 'equipment', 'marketing', 'salary', 'other', name='expensecategory'), nullable=False),
    sa.Column('reference_number', sa.String(), nullable=True),
    sa.Column('vendor', sa.String(), nullable=True),
    sa.Column('payment_method', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('receipt_url', sa.String(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product',
    sa.Column('phone_model', sa.String(), nullable=False),
    sa.Column('part_type', sa.String(), nullable=False),
    sa.Column('variant', sa.String(), nullable=False),
    sa.Column('last_purchase_cost', sa.Float(), nullable=False),
    sa.Column('suggested_sell_price', sa.Float(), nullable=False),
    sa.Column('low_stock_threshold', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('supplier', sa.String(), nullable=True),
    sa.Column('barcode', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_barcode'), 'product', ['barcode'], unique=True)
    op.create_table('repair',
    sa.Column('customer_name', sa.String(), nullable=False),
    sa.Column('customer_phone', sa.String(), nullable=False),
    sa.Column('customer_email', sa.String(), nullable=True),
    sa.Column('phone_model', sa.String(), nullable=False),
    sa.Column('issue_description', sa.String(), nullable=False),
    sa.Column('technician_notes', sa.String(), nullable=True),
    sa.Column('repair_status', sa.Enum('pending', 'in_progress', 'completed', 'cancelled', name='repairstatus'), nullable=False),
    sa.Column('payment_status', sa.Enum('paid', 'pending', 'partial', name='paymentstatus'), nullable=False),
    sa.Column('date_received', sa.Date(), nullable=False),
    sa.Column('estimated_completion', sa.Date(), nullable=True),
    sa.Column('date_completed', sa.Date(), nullable=True),
    sa.Column('labor_cost', sa.Float(), nullable=False),
    sa.Column('parts_cost', sa.Float(), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('amount_paid', sa.Float(), nullable=False),
    sa.Column('warranty_period', sa.Integer(), nullable=True),
    sa.Column('warranty_expiry', sa.Date(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('assigned_technician', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('admin', 'manager', 'technician', 'cashier', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('repairpart',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('repair_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('quantity_used', sa.Integer(), nullable=False),
    sa.Column('unit_cost', sa.Float(), nullable=False),
    sa.Column('total_cost', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['repair_id'], ['repair.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('return',
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('customer_name', sa.String(), nullable=False),
    sa.Column('customer_phone', sa.String(), nullable=False),
    sa.Column('customer_email', sa.String(), nullable=True),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('action_taken', sa.Enum('refund', 'repair', 'exchange', 'replacement', name='returnaction'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', 'resolved', name='returnstatus'), nullable=False),
    sa.Column('return_date', sa.Date(), nullable=False),
    sa.Column('original_transaction_id', sa.Uuid(), nullable=True),
    sa.Column('refund_amount', sa.Float(), nullable=True),
    sa.Column('replacement_product_id', sa.Uuid(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transaction',
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('transaction_type', sa.Enum('purchase', 'sale', name='transactiontype'), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_cost', sa.Float(), nullable=True),
    sa.Column('unit_price', sa.Float(), nullable=True),
    sa.Column('party_name', sa.String(), nullable=True),
    sa.Column('transport_other_cost', sa.Float(), nullable=False),
    sa.Column('reference_number', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transaction')
    op.drop_table('return')
    op.drop_table('repairpart')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('repair')
    op.drop_index(op.f('ix_product_barcode'), table_name='product')
    op.drop_table('product')
    op.drop_table('expense')
    # ### end Alembic commands ###
